version: '3'
services:
  login:
    build: .
    container_name: login
    depends_on:
      - db
      - redis
    ports:
     - "8080:8080"
    links:
     - db:db
     - redis:redis
  db:
    image: "postgres:latest"
    container_name: loginDb
    environment:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: sa
          POSTGRES_DB: login
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"